using Content.Shared._Duty;
using Content.Shared.CCVar;
using DutyCCVars = Content.Shared.CCVar.DutyCCVars;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class DutyAmbientMusicTab : Control
{
    private static readonly DutyAmbientMusicLevel[] VolumeLevels =
    {
        DutyAmbientMusicLevel.VeryGood,
        DutyAmbientMusicLevel.Good,
        DutyAmbientMusicLevel.Medium,
        DutyAmbientMusicLevel.BelowMedium,
        DutyAmbientMusicLevel.Awful,
        DutyAmbientMusicLevel.HpCritical,
        DutyAmbientMusicLevel.MobCritical,
        DutyAmbientMusicLevel.Combat,
        DutyAmbientMusicLevel.CombatLow,
        DutyAmbientMusicLevel.Death,
    };

    public DutyAmbientMusicTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        foreach (var level in VolumeLevels)
        {
            var slider = new OptionSlider { Title = Loc.GetString(DutyAmbientMusicCVar.GetLocaleKey(level)) };
            SlidersContainer.AddChild(slider);
            Control.AddOptionPercentSlider(
                DutyAmbientMusicCVar.GetVolumeCVar(level),
                slider,
                scale: 1f);
        }

        Control.AddOptionCheckBox(DutyCCVars.DynamicAmbientMusicEnabled, DisableAllCheckBox);
        Control.AddOptionCheckBox(DutyCCVars.DynamicAmbientMusicPeacefulDisabled, DisablePeacefulCheckBox);
        Control.AddOptionCheckBox(DutyCCVars.DynamicAmbientMusicCombatDisabled, DisableCombatCheckBox);

        Control.Initialize();
    }
}
