// SPDX-FileCopyrightText: 2025 LocalDuty
// SPDX-License-Identifier: MIT

using System.Linq;
using Content.Shared._Duty.PocketPlayer;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio.Components;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client._Duty.PocketPlayer;

[GenerateTypedNameReferences]
public sealed partial class PocketPlayerMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    private readonly AudioSystem _audioSystem;

    private bool _playState;
    private float _lockTimer;
    private EntityUid? _audio;

    // Громкость: 0..100 → -20..0 dB. Дефолт 100 = 0 dB (без изменений).
    private const float VolumeMin = -20f;
    private const float VolumeMax = 0f;
    private float _currentVolume = 100f;

    private readonly Dictionary<string, (Button Header, BoxContainer Tracks, bool Expanded)> _categories = new();

    public event Action<bool>? OnPlayPressed;
    public event Action? OnStopPressed;
    public event Action<ProtoId<DutyTrackPrototype>>? OnTrackSelected;
    public event Action<float>? SetTime;

    public PocketPlayerMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _audioSystem = _entManager.System<AudioSystem>();

        PlayButton.OnPressed += _ => OnPlayPressed?.Invoke(!_playState);
        StopButton.OnPressed += _ => OnStopPressed?.Invoke();
        PlaybackSlider.OnReleased += OnSliderReleased;

        // Слайдер громкости
        VolumeSlider.SetValueWithoutEvent(_currentVolume);
        VolumeSlider.OnValueChanged += OnVolumeChanged;  // Range.OnValueChanged: Action<Range>

        SetPlayPauseButton(false, force: true);
    }

    /// <summary>
    /// Заполняет дерево категорий и треков.
    /// Треки группируются по полю Category автоматически.
    /// Чтобы добавить новую категорию — просто добавь треки с новым Category в player.yml.
    /// </summary>
    public void Populate(IEnumerable<DutyTrackPrototype> tracks)
    {
        TrackTree.RemoveAllChildren();
        _categories.Clear();

        var grouped = tracks
            .GroupBy(t => t.Category)
            .OrderBy(g => g.Key);

        foreach (var group in grouped)
        {
            var categoryName = group.Key;

            var headerBtn = new Button
            {
                Text = $"▶ {categoryName}",
                HorizontalExpand = true,
                StyleClasses = { "OpenRight" },
                Margin = new Thickness(0, 2, 0, 0),
            };

            var tracksContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 1,
                Margin = new Thickness(16, 0, 0, 4),
                Visible = false,
            };

            foreach (var track in group.OrderBy(t => t.Name))
            {
                var trackId = track.ID;
                var trackBtn = new Button
                {
                    Text = $"  {track.Name}",
                    HorizontalExpand = true,
                    StyleClasses = { "ButtonSmall" },
                };
                trackBtn.OnPressed += _ => OnTrackSelected?.Invoke(trackId);
                tracksContainer.AddChild(trackBtn);
            }

            headerBtn.OnPressed += _ => ToggleCategory(categoryName);

            TrackTree.AddChild(headerBtn);
            TrackTree.AddChild(tracksContainer);

            _categories[categoryName] = (headerBtn, tracksContainer, false);
        }
    }

    private void ToggleCategory(string categoryName)
    {
        if (!_categories.TryGetValue(categoryName, out var entry))
            return;

        var expanded = !entry.Expanded;
        entry.Tracks.Visible = expanded;
        entry.Header.Text = expanded
            ? $"▼ {categoryName}"
            : $"▶ {categoryName}";

        _categories[categoryName] = (entry.Header, entry.Tracks, expanded);
    }

    public void SetAudioStream(EntityUid? audio)
    {
        _audio = audio;
        // Применяем текущую громкость сразу при смене потока
        ApplyVolume();
    }

    public void SetSelectedTrack(string name, float length)
    {
        SongName.Text = string.IsNullOrEmpty(name) ? "--- не выбрано ---" : name;
        PlaybackSlider.MaxValue = length;
        PlaybackSlider.SetValueWithoutEvent(0);
    }

    public void SetPlayPauseButton(bool playing, bool force = false)
    {
        if (_playState == playing && !force)
            return;

        _playState = playing;
        PlayButton.Text = playing ? "⏸ Пауза" : "▶ Играть";
    }

    private void OnSliderReleased(Slider slider)
    {
        SetTime?.Invoke(slider.Value);
        _lockTimer = 0.5f;
    }

    private void OnVolumeChanged(Robust.Client.UserInterface.Controls.Range range)
    {
        _currentVolume = range.Value;
        VolumeLabel.Text = $"{(int) _currentVolume}%";
        ApplyVolume();
    }

    /// <summary>
    /// Применяем громкость напрямую к аудиопотоку на клиенте.
    /// 100% → 0 dB, 0% → -20 dB — не мут, но очень тихо.
    /// </summary>
    private void ApplyVolume()
    {
        if (_audio == null || !_entManager.TryGetComponent(_audio, out AudioComponent? audio))
            return;

        // Линейная интерполяция 0..100 → VolumeMin..вVolumeMax (dB)
        var db = VolumeMin + (_currentVolume / 100f) * (VolumeMax - VolumeMin);
        audio.Volume = db;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_lockTimer > 0f)
            _lockTimer -= args.DeltaSeconds;

        PlaybackSlider.Disabled = _lockTimer > 0f;

        if (_entManager.TryGetComponent(_audio, out AudioComponent? audio))
        {
            DurationLabel.Text =
                $@"{TimeSpan.FromSeconds(audio.PlaybackPosition):mm\:ss} / {_audioSystem.GetAudioLength(audio.FileName):mm\:ss}";

            if (!PlaybackSlider.Grabbed)
                PlaybackSlider.SetValueWithoutEvent(audio.PlaybackPosition);

            SetPlayPauseButton(_audioSystem.IsPlaying(_audio, audio));

            // Удерживаем громкость после возможной перезаписи сервером
            ApplyVolume();
        }
        else
        {
            DurationLabel.Text = "00:00 / 00:00";
            if (!PlaybackSlider.Grabbed)
                PlaybackSlider.SetValueWithoutEvent(0f);

            SetPlayPauseButton(false);
        }
    }
}
