using System.Linq;
using Content.Shared._Duty.HealthPhrases;
using Robust.Client.Graphics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Duty.HealthPhrases;

internal enum PhraseLevel
{
    Level70,
    Level55,
    Level40,
    Level25,
    Level10,
    Level5,
}

internal enum PhraseKind
{
    Popup,
    Whisper,
}

[GenerateTypedNameReferences]
public sealed partial class HealthPhrasesTab : Control
{
    public event Action<HealthPhrasesData>? OnPhrasesChanged;

    private readonly Dictionary<(PhraseLevel, PhraseKind), TextEdit> _inputs = new();
    private bool _suppressChanges;

    public HealthPhrasesTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        LevelsContainer.AddChild(new Label
        {
            Text = Loc.GetString("duty-health-phrases-tab-title"),
            StyleClasses = { "LabelHeading" },
            Margin = new Thickness(0, 0, 0, 4),
        });
        LevelsContainer.AddChild(new Label
        {
            Text = Loc.GetString("duty-health-phrases-tab-hint"),
            Margin = new Thickness(0, 0, 0, 8),
        });

        AddLevel(PhraseLevel.Level70, "duty-health-phrases-level-70");
        AddLevel(PhraseLevel.Level55, "duty-health-phrases-level-55");
        AddLevel(PhraseLevel.Level40, "duty-health-phrases-level-40");
        AddLevel(PhraseLevel.Level25, "duty-health-phrases-level-25");
        AddLevel(PhraseLevel.Level10, "duty-health-phrases-level-10");
        AddLevel(PhraseLevel.Level5, "duty-health-phrases-level-5");
    }

    private void AddLevel(PhraseLevel level, string locKey)
    {
        var panel = new PanelContainer { HorizontalExpand = true };
        panel.PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#2d2d2d") };

        var box = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(10),
            HorizontalExpand = true,
        };

        box.AddChild(new Label
        {
            Text = Loc.GetString(locKey),
            StyleClasses = { "LabelHeading" },
            Margin = new Thickness(0, 0, 0, 8),
        });

        AddPhraseField(box, level, PhraseKind.Popup, "duty-health-phrases-popup-label");
        AddPhraseField(box, level, PhraseKind.Whisper, "duty-health-phrases-whisper-label");

        panel.AddChild(box);
        LevelsContainer.AddChild(panel);
    }

    private void AddPhraseField(BoxContainer parent, PhraseLevel level, PhraseKind kind, string locKey)
    {
        parent.AddChild(new Label
        {
            Text = Loc.GetString(locKey),
            Margin = new Thickness(0, 4, 0, 4),
        });

        var input = new TextEdit
        {
            HorizontalExpand = true,
            MinHeight = 56,
            Placeholder = new Rope.Leaf(Loc.GetString("duty-health-phrases-placeholder")),
        };

        input.OnTextChanged += _ =>
        {
            if (_suppressChanges)
                return;

            OnPhrasesChanged?.Invoke(CollectData());
        };

        parent.AddChild(input);
        _inputs[(level, kind)] = input;
    }

    public void SetData(HealthPhrasesData data)
    {
        _suppressChanges = true;
        try
        {
            SetField(PhraseLevel.Level70, PhraseKind.Popup, data.Popup70);
            SetField(PhraseLevel.Level70, PhraseKind.Whisper, data.Whisper70);
            SetField(PhraseLevel.Level55, PhraseKind.Popup, data.Popup55);
            SetField(PhraseLevel.Level55, PhraseKind.Whisper, data.Whisper55);
            SetField(PhraseLevel.Level40, PhraseKind.Popup, data.Popup40);
            SetField(PhraseLevel.Level40, PhraseKind.Whisper, data.Whisper40);
            SetField(PhraseLevel.Level25, PhraseKind.Popup, data.Popup25);
            SetField(PhraseLevel.Level25, PhraseKind.Whisper, data.Whisper25);
            SetField(PhraseLevel.Level10, PhraseKind.Popup, data.Popup10);
            SetField(PhraseLevel.Level10, PhraseKind.Whisper, data.Whisper10);
            SetField(PhraseLevel.Level5, PhraseKind.Popup, data.Popup5);
            SetField(PhraseLevel.Level5, PhraseKind.Whisper, data.Whisper5);
        }
        finally
        {
            _suppressChanges = false;
        }
    }

    private void SetField(PhraseLevel level, PhraseKind kind, List<string> phrases)
    {
        if (!_inputs.TryGetValue((level, kind), out var input))
            return;

        input.TextRope = new Rope.Leaf(string.Join("\n", phrases));
    }

    private HealthPhrasesData CollectData() => new()
    {
        Popup70 = ParsePhrases(GetInputText(PhraseLevel.Level70, PhraseKind.Popup)),
        Whisper70 = ParsePhrases(GetInputText(PhraseLevel.Level70, PhraseKind.Whisper)),
        Popup55 = ParsePhrases(GetInputText(PhraseLevel.Level55, PhraseKind.Popup)),
        Whisper55 = ParsePhrases(GetInputText(PhraseLevel.Level55, PhraseKind.Whisper)),
        Popup40 = ParsePhrases(GetInputText(PhraseLevel.Level40, PhraseKind.Popup)),
        Whisper40 = ParsePhrases(GetInputText(PhraseLevel.Level40, PhraseKind.Whisper)),
        Popup25 = ParsePhrases(GetInputText(PhraseLevel.Level25, PhraseKind.Popup)),
        Whisper25 = ParsePhrases(GetInputText(PhraseLevel.Level25, PhraseKind.Whisper)),
        Popup10 = ParsePhrases(GetInputText(PhraseLevel.Level10, PhraseKind.Popup)),
        Whisper10 = ParsePhrases(GetInputText(PhraseLevel.Level10, PhraseKind.Whisper)),
        Popup5 = ParsePhrases(GetInputText(PhraseLevel.Level5, PhraseKind.Popup)),
        Whisper5 = ParsePhrases(GetInputText(PhraseLevel.Level5, PhraseKind.Whisper)),
    };

    private string GetInputText(PhraseLevel level, PhraseKind kind) =>
        _inputs.TryGetValue((level, kind), out var input) ? Rope.Collapse(input.TextRope) : string.Empty;

    private static List<string> ParsePhrases(string text) =>
        text.Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries).ToList();
}
