using System.Linq;
using Content.Shared._Duty.HealthPhrases;
using Robust.Client.Graphics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Duty.HealthPhrases;

[GenerateTypedNameReferences]
public sealed partial class HealthPhrasesTab : Control
{
    public event Action<HealthPhrasesData>? OnPhrasesChanged;

    private readonly Dictionary<string, TextEdit> _inputs = new();
    private bool _suppressChanges;

    public HealthPhrasesTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        LevelsContainer.AddChild(new Label
        {
            Text = Loc.GetString("duty-health-phrases-tab-title"),
            StyleClasses = { "LabelHeading" },
            Margin = new Thickness(0, 0, 0, 4),
        });
        LevelsContainer.AddChild(new Label
        {
            Text = Loc.GetString("duty-health-phrases-tab-hint"),
            Margin = new Thickness(0, 0, 0, 8),
        });

        AddLevel("70", "duty-health-phrases-level-70");
        AddLevel("55", "duty-health-phrases-level-55");
        AddLevel("40", "duty-health-phrases-level-40");
        AddLevel("25", "duty-health-phrases-level-25");
        AddLevel("10", "duty-health-phrases-level-10");
        AddLevel("5", "duty-health-phrases-level-5");
    }

    private void AddLevel(string levelKey, string locKey)
    {
        var panel = new PanelContainer { HorizontalExpand = true };
        panel.PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#2d2d2d") };

        var box = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(10),
            HorizontalExpand = true,
        };

        box.AddChild(new Label
        {
            Text = Loc.GetString(locKey),
            StyleClasses = { "LabelHeading" },
            Margin = new Thickness(0, 0, 0, 8),
        });

        AddPhraseField(box, levelKey, "Popup", "duty-health-phrases-popup-label");
        AddPhraseField(box, levelKey, "Whisper", "duty-health-phrases-whisper-label");

        panel.AddChild(box);
        LevelsContainer.AddChild(panel);
    }

    private void AddPhraseField(BoxContainer parent, string levelKey, string typeKey, string locKey)
    {
        parent.AddChild(new Label
        {
            Text = Loc.GetString(locKey),
            Margin = new Thickness(0, 4, 0, 4),
        });

        var input = new TextEdit
        {
            HorizontalExpand = true,
            MinHeight = 56,
            Placeholder = new Rope.Leaf(Loc.GetString("duty-health-phrases-placeholder")),
        };

        input.OnTextChanged += _ =>
        {
            if (_suppressChanges)
                return;

            OnPhrasesChanged?.Invoke(CollectData());
        };

        parent.AddChild(input);
        _inputs[$"{levelKey}_{typeKey}"] = input;
    }

    public void SetData(HealthPhrasesData data)
    {
        _suppressChanges = true;
        try
        {
            SetField("70", "Popup", data.Popup70);
            SetField("70", "Whisper", data.Whisper70);
            SetField("55", "Popup", data.Popup55);
            SetField("55", "Whisper", data.Whisper55);
            SetField("40", "Popup", data.Popup40);
            SetField("40", "Whisper", data.Whisper40);
            SetField("25", "Popup", data.Popup25);
            SetField("25", "Whisper", data.Whisper25);
            SetField("10", "Popup", data.Popup10);
            SetField("10", "Whisper", data.Whisper10);
            SetField("5", "Popup", data.Popup5);
            SetField("5", "Whisper", data.Whisper5);
        }
        finally
        {
            _suppressChanges = false;
        }
    }

    private void SetField(string levelKey, string typeKey, List<string> phrases)
    {
        if (!_inputs.TryGetValue($"{levelKey}_{typeKey}", out var input))
            return;

        input.TextRope = new Rope.Leaf(string.Join("\n", phrases));
    }

    private HealthPhrasesData CollectData() => new()
    {
        Popup70 = ParsePhrases(GetInputText("70", "Popup")),
        Whisper70 = ParsePhrases(GetInputText("70", "Whisper")),
        Popup55 = ParsePhrases(GetInputText("55", "Popup")),
        Whisper55 = ParsePhrases(GetInputText("55", "Whisper")),
        Popup40 = ParsePhrases(GetInputText("40", "Popup")),
        Whisper40 = ParsePhrases(GetInputText("40", "Whisper")),
        Popup25 = ParsePhrases(GetInputText("25", "Popup")),
        Whisper25 = ParsePhrases(GetInputText("25", "Whisper")),
        Popup10 = ParsePhrases(GetInputText("10", "Popup")),
        Whisper10 = ParsePhrases(GetInputText("10", "Whisper")),
        Popup5 = ParsePhrases(GetInputText("5", "Popup")),
        Whisper5 = ParsePhrases(GetInputText("5", "Whisper")),
    };

    private string GetInputText(string levelKey, string typeKey) =>
        _inputs.TryGetValue($"{levelKey}_{typeKey}", out var input) ? Rope.Collapse(input.TextRope) : string.Empty;

    private static List<string> ParsePhrases(string text) =>
        text.Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries).ToList();
}
